"""empty message
Revision ID: cab8e660ccf4
Revises: d0cfefac37b0
Create Date: 2021-11-16 13:56:54.105900
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab8e660ccf4'
down_revision = 'd0cfefac37b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=40), nullable=False),
    # sa.Column('email', sa.String(length=255), nullable=False),
    # sa.Column('hashed_password', sa.String(length=255), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('username')
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
